name: renv
channels:
  - conda-forge
  - defaults
  - R
dependencies:
  - r-base=4.2.3
  - r-tidyverse=1.3.1
  - r-gganimate
  - r-plotly
  - r-essentials
  - r-desolve
  - r-ggplot2
  - r-reshape2
  - r-fme 
  - rstudio-desktop